# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 251f29f1ff88a1af11d2094141363eca1b38a4dd7255d8ae4828bb9b9ffb21c98832cf683f393ef0db38b400f07e22d8c320e411352ce486408b0510aadab8c3

test:
  secret_key_base: 65ebb6f574ecf8dee54e8a45403e5e4a7c32608d9b10b0e35e2971e1a5fdd673bcb24c2f6dbb40867699b57d15d80dcee6145b8ed0951bea1a493c859417b3e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
